#ifndef GFX_ENUM_H
#define GFX_ENUM_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

	typedef enum gfx_queue_capability_flag {
		GFX_QUEUE_CAPABILITY_NONE = 0,
		GFX_QUEUE_CAPABILITY_GRAPHICS = 0x01,	// Graphics operations
		GFX_QUEUE_CAPABILITY_COMPUTE = 0x02,	// Compute shader dispatch
		GFX_QUEUE_CAPABILITY_TRANSFER = 0x04,	// Transfer/copy operations (implicit in Graphics/Compute)
		GFX_QUEUE_CAPABILITY_PRESENT = 0x08,	// Surface presentation support
		GFX_QUEUE_CAPABILITY_SPARSE_BINDING = 0x10,	// Sparse memory binding
		GFX_QUEUE_CAPABILITY_PROTECTED = 0x20,	// Protected memory operations
		GFX_QUEUE_CAPABILITY_VIDEO_DECODE = 0x40,	// Video decode operations
		GFX_QUEUE_CAPABILITY_VIDEO_ENCODE = 0x80,	// Video encode operations
		GFX_QUEUE_CAPABILITY_OPTICAL_FLOW = 0x40,	// NVIDIA optical flow
	} gfx_queue_capability_flag_t;

	typedef uint16_t gfx_queue_capability_flags_t;

	typedef enum gfx_queue_selection_strategy {
		GFX_QUEUE_SELECTION_STRATEGY_EXACT,				// Must match exactly the requested capabilities
		GFX_QUEUE_SELECTION_STRATEGY_MINIMAL,				// Must have at least these capabilities
		GFX_QUEUE_SELECTION_STRATEGY_PREFER_DEDICATED,		// Prefer queues with only requested capabilities
		GFX_QUEUE_SELECTION_STRATEGY_PREFER_SHARED			// Prefer queues with additional capabilities
	} gfx_queue_selection_strategy_t;

	typedef enum gfx_buffer_flag {
		GFX_BUFFER_FLAG_NONE = 0,
		GFX_BUFFER_FLAG_READBACK = 0x01,
		GFX_BUFFER_FLAG_STAGING = 0x02,
		GFX_BUFFER_FLAG_DYNAMIC = 0x04,
		GFX_BUFFER_FLAG_VERTEX = 0x08,
		GFX_BUFFER_FLAG_INDEX = 0x10,
		GFX_BUFFER_FLAG_UNIFORM = 0x20,
		GFX_BUFFER_FLAG_STORAGE = 0x40,
		GFX_BUFFER_FLAG_INDIRECT = 0x80,
		GFX_BUFFER_FLAG_ACCELERATION_BUILD = 0x100,
		GFX_BUFFER_FLAG_ACCELERATION_STORE = 0x200,
		GFX_BUFFER_FLAG_SHADER_BINDING_TABLE = 0x400,
	} gfx_buffer_flag_t;

	typedef uint16_t gfx_buffer_flags_t;

	typedef enum gfx_image_flag_t {
		GFX_IMAGE_FLAG_NONE = 0,
		GFX_IMAGE_FLAG_SAMPLE = 0x01,
		GFX_IMAGE_FLAG_COPY_SOURCE = 0x02,
		GFX_IMAGE_FLAG_COPY_TARGET = 0x04,
		GFX_IMAGE_FLAG_COPY_STORAGE = 0x08,
		GFX_IMAGE_FLAG_WRITE_COLOR = 0x10,
	};

	typedef uint16_t gfx_image_flags_t;

	typedef enum gfx_resource_state_flag {
		GFX_RESOURCE_STATE_UNDEFINED = 0,

		GFX_RESOURCE_STATE_VERTEX_READ = 0x01,
		GFX_RESOURCE_STATE_INDEX_READ = 0x02,

		GFX_RESOURCE_STATE_RENDER_TARGET = 0x04,
		GFX_RESOURCE_STATE_UNORDERED_ACCESS = 0x08,

		GFX_RESOURCE_STATE_DEPTH_WRITE = 0x10,
		GFX_RESOURCE_STATE_DEPTH_READ = 0x20,
		GFX_RESOURCE_STATE_STENCIL_WRITE = 0x40,
		GFX_RESOURCE_STATE_STENCIL_READ = 0x80,

		GFX_RESOURCE_STATE_DEPTH_STENCIL_WRITE = GFX_RESOURCE_STATE_DEPTH_WRITE | GFX_RESOURCE_STATE_STENCIL_WRITE,
		GFX_RESOURCE_STATE_DEPTH_STENCIL_READ = GFX_RESOURCE_STATE_DEPTH_READ | GFX_RESOURCE_STATE_STENCIL_READ,

		GFX_RESOURCE_STATE_NON_GRAPHICS_SHADER = 0x100,
		GFX_RESOURCE_STATE_GRAPHICS_SHADER = 0x200,
		GFX_RESOURCE_STATE_SHADER_RESOURCE = GFX_RESOURCE_STATE_NON_GRAPHICS_SHADER | GFX_RESOURCE_STATE_GRAPHICS_SHADER,

		GFX_RESOURCE_STATE_INDIRECT_ARGUMENT = 0x400,
		GFX_RESOURCE_STATE_COPY_DST = 0x800,
		GFX_RESOURCE_STATE_COPY_SRC = 0x1000,
		GFX_RESOURCE_STATE_PRESENT = 0x2000,

		GFX_RESOURCE_STATE_ACCELERATION_READ = 0x4000,
		GFX_RESOURCE_STATE_ACCELERATION_WRITE = 0x8000,
	} gfx_resource_state_flag_t;

	typedef uint32_t gfx_resource_state_flags_t;

#ifdef __cplusplus
}
#endif

#endif // GFX_ENUM_H